Repository ZhivaevArtem/SiliciumBot, pull requests merged in 2022-02, with the labels that each got.

#11 Refactor/issue 7 reimplement with java
  .editorconfig
  .github/workflows/build-test.yml
  .github/workflows/increment-version.yml
  .gitignore
  pom.xml
  src/main/java/com/zhivaevartem/siliciumbot/App.java
  src/test/java/com/zhivaevartem/siliciumbot/AppTest.java
Labels: refactor

#12 issue-7: Cache maven deps
  .github/workflows/build-test.yml
  .github/workflows/increment-version.yml
Labels: refactor

#21 issue-16: Sample bot
  .github/workflows/build-test.yml
  pom.xml
  src/main/java/com/zhivaevartem/siliciumbot/App.java
  src/main/java/com/zhivaevartem/siliciumbot/listeners/SampleEventListener.java
  src/main/java/com/zhivaevartem/siliciumbot/utils/ConfigUtils.java
  src/main/resources/application.properties
Labels: development

#23 issue-22: Automatically code style checks
  pom.xml
  src/main/java/com/zhivaevartem/siliciumbot/App.java
  src/main/java/com/zhivaevartem/siliciumbot/listeners/SampleEventListener.java
  src/main/java/com/zhivaevartem/siliciumbot/utils/ConfigUtils.java
  src/main/resources/google_checks.xml
  src/main/resources/sun_checks.xml
Labels: enhancement

#24 Refactor/issue 17 server spaces
  .editorconfig
  .gitattributes
  .gitignore
  pom.xml
  src/main/java/com/zhivaevartem/siliciumbot/App.java
  src/main/java/com/zhivaevartem/siliciumbot/persistence/entities/BotConfigLocal.java
  src/main/java/com/zhivaevartem/siliciumbot/persistence/services/BotConfigLocalService.java
  src/main/java/com/zhivaevartem/siliciumbot/persistence/services/ServiceBase.java
  src/main/java/com/zhivaevartem/siliciumbot/utils/ConfigUtils.java
  src/main/resources/META-INF/persistence.xml
Labels: refactor
